# Generated by Django 3.2.6 on 2022-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220307_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/autor'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner'),
        ),
        migrations.AlterField(
            model_name='galarey',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/galarey'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='media/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner'),
        ),
    ]
